# Generated by Django 3.2.13 on 2023-08-20 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='cliente',
        ),
        migrations.CreateModel(
            name='ClienteEndereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos_associados', to='API.cliente')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_associados', to='API.endereco')),
            ],
        ),
    ]
