# Generated by Django 3.2.20 on 2023-08-20 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_endereco_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='cliente',
        ),
    ]
