# Generated by Django 3.2.20 on 2023-08-20 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_remove_endereco_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='clientes',
            field=models.ManyToManyField(through='API.ClienteEndereco', to='API.Cliente'),
        ),
        migrations.AlterField(
            model_name='clienteendereco',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.cliente'),
        ),
        migrations.AlterField(
            model_name='clienteendereco',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.endereco'),
        ),
    ]
