# Generated by Django 3.2.20 on 2023-08-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_auto_20230820_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='enderecos',
            field=models.TextField(default='[]'),
        ),
    ]
