# Generated by Django 3.2.20 on 2023-08-20 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_alter_cliente_enderecos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='enderecos',
        ),
        migrations.AddField(
            model_name='endereco',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='API.cliente'),
        ),
    ]
