# Generated by Django 3.2.20 on 2023-08-20 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_auto_20230820_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='cliente',
        ),
    ]
