# Generated by Django 3.2.20 on 2023-08-20 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_remove_endereco_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_associados', to='API.endereco'),
        ),
        migrations.AlterField(
            model_name='clienteendereco',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos_clientes', to='API.endereco'),
        ),
    ]
