# Generated by Django 3.2.20 on 2023-08-20 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0017_auto_20230820_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='enderecos',
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.endereco'),
        ),
        migrations.AlterField(
            model_name='clienteendereco',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos_associados', to='API.cliente'),
        ),
        migrations.AlterField(
            model_name='clienteendereco',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_associados', to='API.endereco'),
        ),
    ]
