# Generated by Django 3.2.20 on 2023-08-20 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0018_auto_20230820_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='id_endereco',
        ),
        migrations.AddField(
            model_name='cliente',
            name='enderecos',
            field=models.ManyToManyField(related_name='clientes', to='API.Endereco'),
        ),
    ]
