# Generated by Django 3.2.20 on 2023-08-20 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0019_auto_20230820_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='id_endereco',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
